export enum TasksActionTypes {
  FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST",
  RECIVE_ALL_TASKS = "RECIVE_ALL_TASKS",
  RECIVE_TASK_BY_ID = "RECIVE_TASK_BY_ID",
  RECIVE_CREATE_TASK = "RECIVE_CREATE_TASK",
  RECIVE_UPDATE_TASK = "RECIVE_UPDATE_TASK",
  DELETE_TASK = "DELETE_TASK",
  SUCCES_FETCH_REQUEST = "SUCCES_FETCH_REQUEST",
  FAILURE_FETCH_REQUEST = "FAILURE_FETCH_REQUEST"
}
